import { promises as fs } from 'node:fs';
import path from 'node:path';
import { createSupabaseAdminClient } from '@/server/supabase-admin';

type LegacyWord = {
  english: string;
  welsh: string;
  type: string;
};

type LegacyPayload = { words: LegacyWord[] };

type WordInsert = {
  english: string;
  welsh: string;
  legacy_type: string;
  part_of_speech: string;
  frequency_rank: number | null;
  notes: string | null;
};

const ROOT = process.cwd();
const INPUT_PATH = path.join(ROOT, 'data.json');
const OUTPUT_JSON_PATH = path.join(ROOT, 'supabase/seed/legacy-words.json');
const OUTPUT_SQL_PATH = path.join(ROOT, 'supabase/seed/legacy-seed.sql');
const APPLY_FLAG = '--apply';
const WIPE_FLAG = '--wipe';

const PART_OF_SPEECH_MAP: Record<string, string> = {
  nouns: 'noun',
  adjectives: 'adjective',
  verb_infinitives: 'verb_infinitive',
  preterite_conjugations: 'conjugation',
  present_tense_conjugations: 'conjugation',
  whole_phrases: 'phrase',
  time_expressions: 'phrase',
};

function escapeSql(value: string): string {
  return value.replaceAll("'", "''");
}

async function buildWords() {
  const raw = await fs.readFile(INPUT_PATH, 'utf-8');
  const payload = JSON.parse(raw) as LegacyPayload;

  return payload.words.map((word) => ({
    english: word.english.trim(),
    welsh: word.welsh.trim(),
    legacy_type: word.type,
    part_of_speech: PART_OF_SPEECH_MAP[word.type] ?? 'phrase',
    frequency_rank: null,
    notes: null,
  })) satisfies WordInsert[];
}

async function writeSeedFiles(words: WordInsert[]) {
  const categorySet = new Set(words.map((word) => word.legacy_type));

  const seedSqlLines = [
    '-- Generated by scripts/migrate-legacy-json.ts',
    'begin;',
    ...Array.from(categorySet).map(
      (category) =>
        `insert into public.categories (name) values ('${escapeSql(category)}') on conflict (name) do nothing;`,
    ),
    ...words.map(
      (word) =>
        `with inserted as (\n` +
        `  insert into public.words (welsh, english, part_of_speech, frequency_rank, legacy_type, notes)\n` +
        `  values ('${escapeSql(word.welsh)}', '${escapeSql(word.english)}', '${escapeSql(word.part_of_speech)}', null, '${escapeSql(word.legacy_type)}', null)\n` +
        `  returning id, legacy_type\n` +
        `)\n` +
        `insert into public.word_categories (word_id, category_id)\n` +
        `select inserted.id, c.id from inserted join public.categories c on c.name = inserted.legacy_type\n` +
        `on conflict do nothing;`,
    ),
    'commit;',
    '',
  ];

  await fs.writeFile(OUTPUT_JSON_PATH, JSON.stringify({ words }, null, 2));
  await fs.writeFile(OUTPUT_SQL_PATH, seedSqlLines.join('\n'));
}

async function seedSupabase(words: WordInsert[], shouldWipe: boolean) {
  if (!shouldWipe) {
    throw new Error(
      'Direct imports require --wipe so the legacy dataset can be reseeded safely without duplicates.',
    );
  }

  const categoryNames = Array.from(new Set(words.map((word) => word.legacy_type))).sort();
  const supabaseAdmin = createSupabaseAdminClient();

  const { error: deleteWordCategoriesError } = await supabaseAdmin
    .from('word_categories')
    .delete()
    .not('word_id', 'is', null);

  if (deleteWordCategoriesError) {
    throw deleteWordCategoriesError;
  }

  const { error: deleteWordsError } = await supabaseAdmin.from('words').delete().not('id', 'is', null);

  if (deleteWordsError) {
    throw deleteWordsError;
  }

  const { error: deleteCategoriesError } = await supabaseAdmin
    .from('categories')
    .delete()
    .not('id', 'is', null);

  if (deleteCategoriesError) {
    throw deleteCategoriesError;
  }

  const { data: insertedCategories, error: insertCategoriesError } = await supabaseAdmin
    .from('categories')
    .insert(categoryNames.map((name) => ({ name })))
    .select('id, name');

  if (insertCategoriesError) {
    throw insertCategoriesError;
  }

  const categoryIdByName = new Map(insertedCategories.map((category) => [category.name, category.id]));
  let insertedWordCount = 0;

  for (const word of words) {
    const { data: insertedWord, error: insertWordError } = await supabaseAdmin
      .from('words')
      .insert(word)
      .select('id')
      .single();

    if (insertWordError) {
      throw insertWordError;
    }

    const categoryId = categoryIdByName.get(word.legacy_type);

    if (!categoryId) {
      throw new Error(`Missing category mapping for legacy type: ${word.legacy_type}`);
    }

    const { error: insertWordCategoryError } = await supabaseAdmin.from('word_categories').insert({
      word_id: insertedWord.id,
      category_id: categoryId,
    });

    if (insertWordCategoryError) {
      throw insertWordCategoryError;
    }

    insertedWordCount += 1;
  }

  console.log('Applied legacy import to Supabase with wipe-and-reseed mode.');
  console.log(`Inserted ${insertedWordCount} words across ${categoryNames.length} categories.`);
}

function hasFlag(flag: string) {
  return process.argv.includes(flag);
}

async function main() {
  const words = await buildWords();
  const shouldApply = hasFlag(APPLY_FLAG);
  const shouldWipe = hasFlag(WIPE_FLAG);

  await writeSeedFiles(words);

  console.log(`Converted ${words.length} words from legacy JSON.`);
  console.log(`Wrote: ${path.relative(ROOT, OUTPUT_JSON_PATH)}`);
  console.log(`Wrote: ${path.relative(ROOT, OUTPUT_SQL_PATH)}`);

  if (shouldApply) {
    await seedSupabase(words, shouldWipe);
  } else if (shouldWipe) {
    console.log(`Skipped Supabase import because ${APPLY_FLAG} was not provided.`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
